BARS/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using BARS.Models;

namespace BARS.Controllers
{
    public class OperationsController : ApiController
    {


        private readonly IRepository<Operation> db3;

        public OperationsController(IRepository<Operation> r3)
        {

            db3 = r3;
        }

        // GET: api/Operations
        public IEnumerable<OperationViewModel> GetOperations()
        {
            List<OperationViewModel> operViewModels = new List<OperationViewModel>();

            var opers = db3.GetItemsList();
            foreach (var oper in opers)
            {
                var operViewModel = new OperationViewModel
                {
                    Id = oper.Id,
                    Date = oper.Date,
                    Action = oper.Action,
                    Amount = oper.Amount,
                    BillFromId = oper.BillFromId,
                    BillToId = oper.BillToId,
                    BillFromName = oper.BillFrom.Name,
                    BillToName = oper.BillTo.Name,
                    OrganisationFromName = oper.BillFrom.Organisation.Name,
                    OrganisationToName = oper.BillTo.Organisation.Name,
                };
                operViewModels.Add(operViewModel);
            }
                
            return operViewModels;
        }

        // GET: api/Operations/5
        public Operation GetOperations(int id)
        {
            Operation operation = db3.GetItem(id);
            return operation;
        }

        // POST: api/Operations
        public void PostOperation([FromBody]Operation operation)
        {
            DateTime date = DateTime.Now;
            Operation oper = new Operation
            {
                Id = operation.Id,
                Date = date,
                Action = operation.Action,
                Amount = operation.Amount,
                BillFromId = operation.BillFromId,
                BillToId = operation.BillToId

            };

            db3.Create(oper);
            //b3.Save();
        }

        // PUT: api/Operations/5
        public void PutOperation(int id, [FromBody]Operation operation)
        {
            if (id == operation.Id)
            {
                db3.Update(operation);

                db3.Save();
            }
        }

        // DELETE: api/Operations/5
        public void DeleteOperation(int id)
        {
            db3.Delete(id);
            db3.Save();
        }
        protected override void Dispose(bool disposing)
        {
            db3.Dispose();
            base.Dispose(disposing);
        }
    }
}

BARS/Controllers/OrganisationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using BARS.Models;

namespace BARS.Controllers
{
    public class OrganisationsController : ApiController
    {

        private readonly IRepository<Organisation> db1;


        public OrganisationsController(IRepository<Organisation> r1)
        {
            db1 = r1;

        }

        public OrganisationsController()
        {

        }
        // GET: api/Values
        [HttpGet]
        public IEnumerable<OrganisationViewModel> GetOrganisations()
        {
            List<OrganisationViewModel> organisationViewModels = new List<OrganisationViewModel>();
            var organisations = db1.GetItemsList();
            foreach (var org in organisations)
            {
                var organisationViewModel = new OrganisationViewModel
                {
                    Id = org.Id,
                    Name = org.Name,
                    Type = org.Type
                };
                organisationViewModels.Add(organisationViewModel);
            }
            return organisationViewModels;
        }

        // GET: api/Values/5
        [HttpGet]
        public OrganisationViewModel GetOrganisation(int id)
        {
            Organisation organisation = db1.GetItem(id);
            return new OrganisationViewModel
            {
                Id = organisation.Id,
                Name = organisation.Name,
                Type = organisation.Type
            };
        }

        // POST: api/Values
        [HttpPost]
        public void PostOrganisation(Organisation organisation)
        {
            db1.Create(organisation);
            db1.Save();
        }

        // PUT: api/Values/5
        [HttpPut]
        public void PutOrganisation(Organisation organisation)
        {
            if (organisation != null && ModelState.IsValid)
            {
                if (organisation.Id != 0)
                {
                    db1.Update(organisation);

                    db1.Save();
                }
            }
            
        }

        // DELETE: api/Values/5
        [HttpDelete]
        public void DeleteOrganisation(Organisation organisation)
        {
            db1.Delete(organisation.Id);
            db1.Save();
        }
        protected override void Dispose(bool disposing)
        {
            db1.Dispose();
            base.Dispose(disposing);
        }
    }
}

BARS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link href="~/Content/kendostyles/kendo.common.min.css" rel="stylesheet" />
    <link href="~/Content/kendostyles/kendo.default.min.css" rel="stylesheet" />

    <script src="~/Scripts/kendojs/kendo.web.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Организации", "Organisations", "Home")</li>
                    <li>@Html.ActionLink("Перевести деньги", "Transfer", "Home")</li>
                    <li>@Html.ActionLink("Операции", "Operations", "Home")</li>
                    

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Web Banking Application. </p>
        </footer>
    </div>

    
</body>
</html>